/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_buluyizhi_apwifi_JavaCallNative */

#ifndef _Included_com_buluyizhi_apwifi_JavaCallNative
#define _Included_com_buluyizhi_apwifi_JavaCallNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_buluyizhi_apwifi_JavaCallNative
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_buluyizhi_apwifi_JavaCallNative_getStringFromC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
